#!/bin/bash
echo "Enter a number to select an action"
echo "1 - nano"
echo "2 - vi"
echo "3 - links"
echo "4 - quit program"
read n
case $n in

1)
nano
;;

2)
vi
;;

3)
links
;;

* )
echo "goodbye"
;;
esac
