#!/bin/bash 

file=$1
tdir="$PWD/.trash"
tlog="$PWD/.trash.log"

if [[ ! -e "$file" ]];
  then 
  echo "Error: file don't exist"
  exit 1
fi 

if [[ $# -ne 1 ]];
  then 
  echo "Error: wrong number of arguments"
  exi 2
fi 

if [[ ! -e $tdir ]];
  then
  mkdir $tdir 
  touch $tlog
fi 

if [[ "$(ls -A "$tdir")" ]];
  then
  count=$(ls -A "$tdir" | wc -l)
  let count="count"+1
else
  count=1
fi

ln "$file" "$tdir/$count"
rm "$file"

printf "%s\t%s\n" "$PWD/$file" "$count" >> $tlog
