#!/bin/bash

file_name="$1"
if [[ -z "file_name" ]]; then
  echo "write name of file"
  exit 1
fi 

while read -r line
do 
  file_path=$(echo -n "$line" | awk -F'\t' '{print $1}')
  trash_name=$(echo -n "$line" | awk -F'\t' '{print $2}')
  cur_file_name=$(basename "$file_path")
  echo $dir

  if [[ "$cur_file_name" != "$file_name" ]]; then
    continue
  fi 

    read -r -u 1 -p "do you want to restore file $file_path y/n " response
    case "$response" in 
      [yY])
        if [[ ! -d "$dir" ]]; then
          dir="$PWD"
        fi 
        while [[ -f "$dir/$cur_file_name" ]]; do 
          read -r -u 1 -p "write another name or write stop " cur_file_name
          if [[ "$cur_file_name" == "stop" ]]; then
            exit 2
          fi 
        done
        ln "$PWD/.trash/$trash_name" "$dir/$cur_file_name"
        rm "$PWD/.trash/$trash_name"
        sed -i "/$trash_name/d" "$PWD/.trash.log"
        exit 0;
        break 
        ;;
      [nN])
        continue
        ;;
      [*])
        exit 3
        ;;
    esac
done < "$PWD/.trash.log"


