#!/bin/bash
PIPE=/tmp/message_pipe

write_message() {
	message=$1
	count=$2
	for((i=0; i<$count; i++)) do
		echo "$message" > pipe
		sleep 1
	done
}

write_message "Море теплое" 4
write_message "Акулы приближаются" 3
write_message "Они здесь" 1

exit 2
